
export const POPULATE_POSTS = "POPULATE_POSTS"

export const POPULATE_SELECTED_POST = "POPULATE_SELECTED_POST"

export const UPDATE_NEW_POST_INPUT = "UPDATE_NEW_POST_INPUT"

export const OPEN_SIDE_DRAWER = "OPEN_SIDE_DRAWER"

export const CLOSE_SIDE_DRAWER = "CLOSE_SIDE_DRAWER"